# Generated by Django 3.2.12 on 2022-05-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodels',
            name='form_uid',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
