# Generated by Django 3.2.12 on 2022-05-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_alter_formmodels_form_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodels',
            name='form_uid',
            field=models.IntegerField(db_index=True, max_length=6, unique=True),
        ),
    ]
